In [1]:
a = [1, 2, 3]
print(a + [4, 5])   # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [2]:
import numpy as np

b = np.array([1, 2, 3])
print(b + np.array([4, 5, 6]))   # [5 7 9]

[5 7 9]


In [3]:
import numpy as np

arr1 = np.array([6, 7.5, 8, 0, 1])
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
arr2 = arr1 * 5
arr2

array([30. , 37.5, 40. ,  0. ,  5. ])

In [5]:
arr3 = arr1 / 10
arr3

array([0.6 , 0.75, 0.8 , 0.  , 0.1 ])